name = "npcc"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["NPCC", "Workspace", "Tests"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "Workspace"

[[lean_lib]]
name = "NPCC"

[[lean_lib]]
name = "Tests"
